spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: ${DB.PROD.DRIVER-CLASS-NAME}
    url: ${DB.PROD.URL}
    username: ${DB.PROD.USERNAME}
    password: ${DB.PROD.PASSWORD}

front:
  server:
    local: ${FRONT.SERVER.LOCAL.URL}
    prod: ${FRONT.SERVER.PROD.URL}

back:
  server:
    local: ${BACK.SERVER.LOCAL.URL}
    api: ${BACK.SERVER.API.URL}
    prod-1: ${BACK.SERVER.PROD-1.URL}
    prod-2: ${BACK.SERVER.PROD-2.URL}

swagger:
  server-url: ${BACK.SERVER.LOCAL.URL}
