name: Spots CD

on:
  workflow_run:
    workflows: [ "Spots CI" ]
    types:
      - completed

jobs:
  deploy:
    name: EC2에 배포
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main' &&
      github.event.workflow_run.event == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: .env 파일 생성
        run: |
          echo "${{ secrets.DOTENV_FILE }}" >> .env

      - name: 배포용 파일 정리
        run: |
          mkdir -p deploy-files
          cp scripts/deploy.sh deploy-files/
          cp nginx/nginx-prod.conf deploy-files/
          cp nginx/nginx-cert-setup.conf deploy-files/
          cp docker-compose.yml deploy-files/
          cp .env deploy-files/

      - name: 필요한 파일들을 EC2 서버로 전송
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.PEM_KEY }}
          source: "deploy-files/*"
          target: "/home/${{ secrets.EC2_USER }}"
          strip_components: 1

      - name: EC2에 접속하여 배포 스크립트 실행
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.PEM_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}
            chmod +x deploy.sh
            ./deploy.sh